---
title             : "2S-PA-Int: Title Page"
shorttitle        : "2S-PA-Int"

author: 
  - name          : "Hok Chio (Mark) Lai"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "3620 McClintock Ave, Los Angeles, CA 90089"
    email         : "hokchiol@usc.edu"

  - name          : "Gengrui (Jimmy) Zhang"
    affiliation   : "1"
    email         : "gengruiz@usc.edu"

affiliation:
  - id            : "1"
    institution   : "University of Southern California"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

## Funding

This research was supported by the National Science Foundation under Grant No. 2141790.
None of the funders or sponsors had any involvement in the design or conduct of the study; the collection, management, analysis, or interpretation of the data; the preparation, review, or approval of the manuscript; or the decision to submit the manuscript for publication.

